#!/usr/bin/env node
'use strict';
/*
 * RENDER THE LEDGER AS A HUMAN VIEW.
 *
 *   node tools/principal-glossary/render-view.js [--out FAMILIARITY.md] [--check]
 *   node tools/principal-glossary/render-view.js --sort        # rewrite ledger.json sorted
 *
 * The JSON is the artifact; FAMILIARITY.md is a rendering of it and is
 * regenerated, never edited by hand. `--check` re-renders and exits nonzero if
 * the committed view has drifted — so a ledger change that forgot to re-render
 * is a failing gate rather than a stale document nobody trusts.
 *
 * `--sort` is the merge helper: after a messy merge, it re-sorts terms by
 * lowercased term and rewrites ledger.json in place, which is the invariant
 * that keeps append-heavy edits from two branches merging line-by-line.
 */

const fs = require('fs');
const path = require('path');
const G = require('./lib/glossary');

const argv = process.argv.slice(2);
const has = (f) => argv.includes(`--${f}`);
function arg(name, dflt) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && i + 1 < argv.length ? argv[i + 1] : dflt;
}

const LEDGER = arg('ledger', null);
const OUT = path.resolve(arg('out', path.join(__dirname, 'FAMILIARITY.md')));

// --sort: rewrite the ledger with terms in canonical order -------------------
if (has('sort')) {
  const p = LEDGER || G.LEDGER_PATH;
  const l = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const pr of l.principals) {
    pr.terms.sort((a, b) => {
      const x = a.term.toLowerCase(), y = b.term.toLowerCase();
      return x < y ? -1 : x > y ? 1 : 0;
    });
  }
  fs.writeFileSync(p, JSON.stringify(l, null, 2) + '\n');
  process.stdout.write(`sorted ${p}\n`);
  process.exit(0);
}

let ledger;
try {
  ledger = G.load(LEDGER);
} catch (e) {
  process.stderr.write(`principal-glossary: ${e.message}\n`);
  process.exit(2);
}

const out = [];
const w = (s = '') => out.push(s);

const STATE_ORDER = ['corrected', 'internal', 'defined', 'native'];
const HEADING = {
  native: 'NATIVE — they used it correctly themselves',
  defined: 'DEFINED — we defined it for them, on a date, somewhere',
  corrected: 'CORRECTED — they told us they did not know it. NEVER use undefined.',
  internal: 'INTERNAL — code / agent-report jargon, NEVER briefed',
};
const RULE = {
  native: 'Safe to use unqualified. Strongest evidence there is.',
  defined: 'Safe to use. A one-clause reminder is still courteous on a long gap.',
  corrected:
    'Must be re-defined at EVERY use, even if it was previously defined. ' +
    'Corrections never auto-expire; only the principal using the term correctly ' +
    'themselves promotes it out of here.',
  internal:
    'Define inline at first use — in the sentence that uses it, not in a glossary ' +
    'appendix — and record the definition event in the ledger in the same work cycle. ' +
    'Or say it in native words instead.',
};

w('<!-- GENERATED by tools/principal-glossary/render-view.js — do not edit.');
w('     Edit ledger.json, then re-render. `--check` fails on drift. -->');
w();
w(`# ${ledger.title}`);
w();
w('Which terminology each human principal has actually been given — so a briefing');
w('can stop assuming and start deducing by elimination.');
w();
w(`Ledger: \`${ledger.home.path}\` on \`${ledger.home.branch}\` · mirror: \`${ledger.home.mirror}\``);
w(`Seeded ${ledger.seededAt} by ${ledger.seededBy}.`);
w();
w('```sh');
w('node tools/principal-glossary/check-briefing.js < draft.md   # before you send it');
w('node tools/principal-glossary/render-view.js                 # after you edit the ledger');
w('```');
w();
w('## The state machine');
w();
w('| state | what it means | what you may do with it |');
w('|---|---|---|');
for (const s of ['native', 'defined', 'corrected', 'internal']) {
  w(`| \`${s}\` | ${ledger.states[s]} | ${RULE[s].replace(/\n/g, ' ')} |`);
}
w();

for (const p of ledger.principals) {
  const counts = {};
  for (const t of p.terms) counts[t.state] = (counts[t.state] || 0) + 1;
  w(`## ${p.displayName || p.id} (\`${p.id}\`${p.role ? `, ${p.role}` : ''})`);
  w();
  w(
    `${p.terms.length} terms tracked: ` +
    STATE_ORDER.filter((s) => counts[s]).map((s) => `**${counts[s]}** ${s}`).join(', ') + '.'
  );
  w();
  const attested = p.terms.filter((t) => {
    const e = t.evidence[t.evidence.length - 1];
    return t.state === 'native' && !e.quote && e.attestation;
  });
  if (attested.length) {
    w(`> **Evidence quality.** ${attested.length} of the ${counts.native} \`native\` terms rest on an`);
    w('> attestation rather than a retained verbatim fragment — seeded from a session');
    w('> transcript that was not quoted line by line. They are the weakest rows here.');
    w('> Upgrade each one with the principal\'s own words the next time they use it.');
    w();
  }

  if (Array.isArray(p.notes) && p.notes.length) {
    w('### Standing corrections and the mandate behind them');
    w();
    for (const n of p.notes) {
      w(`- **${n.date}** (${n.kind}) — "${n.quote}"`);
      w(`  <br>→ ${n.lesson}`);
    }
    w();
  }

  for (const state of STATE_ORDER) {
    const list = p.terms.filter((t) => t.state === state);
    if (!list.length) continue;
    w(`### ${HEADING[state]} (${list.length})`);
    w();
    w(`> ${RULE[state]}`);
    w();
    for (const t of list) {
      const latest = t.evidence[t.evidence.length - 1];
      const aliases = Array.isArray(t.aliases) && t.aliases.length
        ? ` *(also: ${t.aliases.join(', ')})*` : '';
      w(`- **${t.term}**${aliases} — ${t.gloss}`);
      const bits = [latest.date];
      if (latest.where) bits.push(latest.where);
      w(`  <br><sub>${bits.join(' · ')}</sub>`);
      if (latest.quote) w(`  <br><sub>evidence (quoted): "${latest.quote}"</sub>`);
      else if (latest.attestation) w(`  <br><sub>evidence (ATTESTED, no verbatim fragment): ${latest.attestation}</sub>`);
      if (t.note) w(`  <br><sub>NOTE: ${t.note}</sub>`);
      if (t.everCorrected && state !== 'corrected') {
        w('  <br><sub>WAS CORRECTED ONCE — a reminder clause is owed on every use.</sub>');
      }
      if (t.evidence.length > 1) {
        const hist = t.evidence.map((e) => `${e.date} → ${e.to}`).join('; ');
        w(`  <br><sub>history: ${hist}</sub>`);
      }
    }
    w();
  }
}

w('---');
w();
w('## If you are a session that just woke up');
w();
w('Read `tools/principal-glossary/USAGE.md`. The one-line version: **before you');
w('send the owner anything, pipe the draft through `check-briefing.js`; when you');
w('define a term inline, write it into `ledger.json` in the same work cycle.**');
w();

const rendered = out.join('\n');

if (has('check')) {
  let current = '';
  try { current = fs.readFileSync(OUT, 'utf8'); } catch (e) { /* missing */ }
  if (current !== rendered) {
    process.stderr.write(
      `principal-glossary: ${path.basename(OUT)} has drifted from ledger.json.\n` +
      '  Re-run: node tools/principal-glossary/render-view.js\n'
    );
    process.exit(1);
  }
  process.stdout.write(`${path.basename(OUT)} is in sync with the ledger.\n`);
  process.exit(0);
}

fs.writeFileSync(OUT, rendered);
process.stdout.write(`wrote ${OUT}\n`);
