#!/usr/bin/env node
/*
 * BUILD THE TERRITORY WASM KERNELS.
 *
 *   npm run build:wasm
 *
 * Compiles `wasm/assembly/territory.ts` (AssemblyScript, deliberately outside
 * `src/` — see its header) into three COMMITTED artifacts:
 *
 *   wasm/territory.wasm        the module, for anyone who wants to disassemble
 *   wasm/territory.wat         its text form, so a reviewer can read what ships
 *   src/lobster/wasm/module.ts the same bytes as base64, plus the two digests
 *
 * ── WHY THE BYTES ARE ALSO A .ts FILE ──────────────────────────────────────
 *
 * `tsc` copies no assets: `rootDir` is `src/` and `outDir` is `dist/`, so a
 * `.wasm` next to a `.ts` simply is not there after a build, and a runtime
 * `readFileSync` would resolve differently under ts-jest, ts-node and `dist/`.
 * A base64 constant in a generated module is the one form that loads
 * identically in all three and needs no build-time asset step at all.
 *
 * ── WHY THE DIGESTS ────────────────────────────────────────────────────────
 *
 * The artifact is committed, so the build needs no network and no toolchain on
 * the normal path — but a committed artifact can go stale against its source
 * silently. `module.ts` therefore carries the SHA-256 of the AssemblyScript
 * source it was built from, and `src/lobster/wasm/module.test.ts` recomputes it
 * from the file on disk. Editing the kernel without rebuilding fails that test
 * WITHOUT needing `asc` installed, which is the property that matters: the gate
 * runs in CI where the devDependency may not be.
 *
 * ── FINDING `asc` ──────────────────────────────────────────────────────────
 *
 * `assemblyscript` is a declared devDependency, so a plain `npm install` puts
 * it where step 1 finds it. `ASC_PATH` is the escape hatch for a checkout that
 * does not want a 40 MB compiler in its tree (binaryen is most of it).
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'wasm', 'assembly', 'territory.ts');
const OUT_WASM = path.join(ROOT, 'wasm', 'territory.wasm');
const OUT_WAT = path.join(ROOT, 'wasm', 'territory.wat');
const OUT_TS = path.join(ROOT, 'src', 'lobster', 'wasm', 'module.ts');

function ascEntry() {
  if (process.env.ASC_PATH) return process.env.ASC_PATH;
  try {
    return require.resolve('assemblyscript/dist/asc.js', { paths: [ROOT] });
  } catch {
    return null;
  }
}

async function main() {
  const entry = ascEntry();
  if (entry === null) {
    console.error(
      '[build-wasm] assemblyscript not found. `npm install` (it is a declared ' +
        'devDependency), or point ASC_PATH at a dist/asc.js.'
    );
    process.exit(2);
  }
  // `asc.js` is an ESM graph with top-level await, so `require()` refuses it.
  const asc = await import(require('url').pathToFileURL(entry).href);
  const { error, stderr, stdout } = await asc.main([
    SRC,
    '--outFile',
    OUT_WASM,
    '--textFile',
    OUT_WAT,
    '--optimize',
    '--optimizeLevel',
    '3',
    '--shrinkLevel',
    '0',
    '--converge',
    '--runtime',
    'stub',
    '--importMemory',
    '--exportStart',
    '_start',
    '--noAssert',
  ]);
  if (error) {
    console.error('[build-wasm] asc failed:', error.message);
    console.error(stderr.toString());
    process.exit(1);
  }
  const out = stdout.toString();
  if (out.trim()) console.log(out);

  const bytes = fs.readFileSync(OUT_WASM);
  const source = fs.readFileSync(SRC);
  const wasmSha = crypto.createHash('sha256').update(bytes).digest('hex');
  const srcSha = crypto.createHash('sha256').update(source).digest('hex');

  // 76 base64 chars a line: under any sane max-len, and diffs stay readable.
  const b64 = bytes.toString('base64');
  const lines = [];
  for (let i = 0; i < b64.length; i += 76) lines.push(`  '${b64.slice(i, i + 76)}'`);

  fs.writeFileSync(
    OUT_TS,
    `/**
 * GENERATED BY \`npm run build:wasm\` — DO NOT EDIT.
 *
 * The bytes of \`wasm/territory.wasm\`, compiled from
 * \`wasm/assembly/territory.ts\`. See \`scripts/build-wasm.js\` for why the
 * artifact is a base64 constant rather than a file read at runtime.
 *
 * \`SOURCE_SHA256\` is the digest of the AssemblyScript source these bytes were
 * built from. \`module.test.ts\` recomputes it from the file on disk, so a
 * kernel edited without a rebuild fails the suite — with no toolchain needed.
 */

/** SHA-256 of \`wasm/assembly/territory.ts\` at build time. */
export const SOURCE_SHA256 = '${srcSha}';

/** SHA-256 of the module bytes below. */
export const WASM_SHA256 = '${wasmSha}';

/** Compiled bytes, base64. ${bytes.length} bytes. */
export const WASM_BASE64 =
${lines.join(' +\n')};
`
  );

  console.log(
    `[build-wasm] ${bytes.length} bytes  wasm ${wasmSha.slice(0, 12)}  source ${srcSha.slice(0, 12)}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
